### ISSUE TITLE
species list character retrieval is very slow. it takes around 12 seconds for a list of 1000 rows. 

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/phylolink#111]
http://www.bugherd.com/projects/62783/tasks/109

**Comment by ala-bugherd** [comment]
﻿
Please note that I am attending the Australian Citizen Science Conference for Thu 23rd and Fri 24th July.

Regards,
Peter D.
Mobile: 0423 040043

**Comment by ala-bugherd** [comment]
Thanks for your message. I am out of the office until Monday 10th August. If the matter is urgent, please contact peter.doherty@csiro.au

**Comment by m-r-c** [comment]
This has been fixed by https://github.com/AtlasOfLivingAustralia/specieslist-webapp/pull/38 from specieslist-webapp

**Comment by ala-bugherd** [comment]
working with acacia tree: Acacia Characters loads quickly. Western Australian Conservation Status still hadn't loaded after 5+ minutes.
