### ISSUE TITLE
add javascript testing framework

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/phylolink#114]
http://www.bugherd.com/projects/62783/tasks/110

**Comment by ala-bugherd** [comment]
fixes #114 BH-110: do not run bootstrap when testing. adding memory datasource.

**Comment by nickdos** [comment]
Commit 5f054be does not appear to include an addition of a JS testing framework. Can you check this is the correct issue to be closed for this commit, Temi?

**Comment by temi** [comment]
that is true. adding unit testing is done here. https://github.com/AtlasOfLivingAustralia/phylolink/tree/unittest. Unfortunately, I do not think I made a like to it using the commit message.

**Comment by ala-bugherd** [comment]
Commit https://github.com/AtlasOfLivingAustralia/phylolink/commit/5b21ca329fc2fe56c7ec7ea24c2b7311164932c8
