### ISSUE TITLE
Replace this text block with something like: "On this page, you can reconcile the tip names of your tree with ALA taxonomy. The system-matched name is listed in the Matched name column. To edit, click on a cell. To save changes, click Save button."

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/phylolink#166]
http://www.bugherd.com/projects/62783/tasks/148

**Comment by ala-bugherd** [comment]
Fixes #166 map OTUs page text (BH-148)

**Comment by temi** [comment]
that is true. adding unit testing is done here. https://github.com/AtlasOfLivingAustralia/phylolink/tree/unittest. Unfortunately, I do not think I made a like to it using the commit message.
