### ISSUE TITLE
Map section not displaying properly in Firefox/IE/Edge

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/phylolink#207]
When loading a Phylolink tree visualisation in Firefox/MS Edge/MS IE, the map section on the right is transposed down. Working OK in Chrome.

![2019-04-24_105659](https://user-images.githubusercontent.com/35747214/56625326-1f63ec00-6680-11e9-87ad-a5f2c0841bb6.png)

**Comment by djtfmartin** [comment]
this is now fixed. thanks @CorinnaPaeper
